# .readthedocs.yml
# Read the Docs configuration file
# Documentation: https://docs.readthedocs.io/en/stable/config-file/v2.html

# Required
version: 2

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Documentation formats (optional)
# formats:
#   - pdf

# Python requirements for building docs
python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .

# Sphinx configuration path
sphinx:
  configuration: doc/source/conf.py

# Build options
# build:
  # Enabling system packages for dependencies that may require additional libraries
 #  apt_packages:
 #   - pandoc
 #   - dvipng
 #   - graphviz  # If diagrams are needed
